# ============================================================================= #
#                                                                               #
#    888                                888      8888888888                     #
#    888                                888      888                            #
#    888                                888      888                            #
#    888      .d88b.   .d8888b  8888b.  888      8888888    88888b.  888  888   #
#    888     d88""88b d88P"        "88b 888      888        888 "88b 888  888   #
#    888     888  888 888      .d888888 888      888        888  888 Y88  88P   #
#    888     Y88..88P Y88b.    888  888 888      888        888  888  Y8bd8P    #
#    88888888 "Y88P"   "Y8888P "Y888888 888      8888888888 888  888   Y88P     #
#                                                                               #
# ============================================================================= #

# Log properties
logging:
    level:
        root: info
        net:
            sp4rkh:
                api: debug

# Spring properties
spring:
    application:
        name: springboot-be-api
    main:
        allow-bean-definition-overriding: true
        banner-mode: console
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false

# Application properties